application: tpbgui
version: 3
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10s"

builtins:
- remote_api: on

inbound_services:
- warmup

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

#- url: /static/django_tables2/.*
#  static_dir: /gaenv_lib/django_tables2/static
#  expiration: '0'

- url: /media/admin
  static_dir: django/contrib/admin/media

- url: /static/admin
  static_dir: django/contrib/admin/static/admin

- url: /static/
  static_dir: static/

- url: /scrape/.*
  script: djangoappengine.main.application
  login: admin

- url: /.*
  login: required
  script: djangoappengine.main.application

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^/.idea/.*$